# Generated by Django 6.0.1 on 2026-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(max_length=64, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=255)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('participants', models.PositiveSmallIntegerField(db_index=True)),
                ('price', models.FloatField(db_index=True)),
                ('accessibility', models.FloatField(db_index=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
