# Generated by Django 4.2.27 on 2026-02-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_accessibility_alter_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
