# Generated by Django 4.2.27 on 2026-02-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_id_alter_activity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('sport', 'Sport'), ('relax', 'Relax'), ('education', 'Education')], db_index=True, max_length=64),
        ),
    ]
